# Generated by Django 4.2.16 on 2024-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_th', models.CharField(max_length=100, null=True)),
                ('name_km', models.CharField(max_length=100, null=True)),
                ('name_de', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_th', models.TextField(null=True)),
                ('description_km', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
        ),
    ]
