# Generated by Django 4.2.16 on 2024-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='address_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='address_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='address_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='address_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='address_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age_th',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email_de',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email_en',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email_km',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email_ru',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email_th',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='gender_de',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='gender_en',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='gender_km',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='gender_ru',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='gender_th',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone_de',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone_km',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone_th',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
