# Generated by Django 4.2.16 on 2024-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_testmodel_address_de_testmodel_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='age_de',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='age_en',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='age_km',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='age_ru',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='age_th',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_de',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_km',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_th',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='phone_de',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='phone_km',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='phone_ru',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='phone_th',
        ),
    ]
