# Generated by Django 4.2.16 on 2024-11-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_remove_testmodel_age_de_remove_testmodel_age_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='gender_de',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='gender_km',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='gender_ru',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='gender_th',
        ),
    ]
